### PR TITLE
Fromdb

### PR DESCRIPTION
**Pull request by johndonor3**
Hey Mike,

I think this is ready to merge. One thing to check for sure: I had to update your new test_cadence_consistency_merge test with max_length parameters. I don't think it matters much there? But worth a quick check.

All tests pass on my machine (I think travis is having problems with the build? I forgot; I tried awhile ago and couldn't get it) and my last new feature works with my local webapp development.

Thanks,
John

### CODE REVIEW

**Comment by johndonor3** [comment]
Also before I forget: I changed a considerable amount about DB interaction for cadences. I think what you had was largely place holder and/or out-of-date? But if you were expecting anything in particular it's worth a quick check. As I said "it works on my machine" (and I think it's been used a little bit at Utah).

**Comment by blanton144** [comment]
Hi John,

The tests pass, but when I try to use the fromdb() method it fails.

The Utah db (correctly) doesn't have instrument in the cadence definition anymore, and so that needs to be fixed.

I can fix that but wanted to check with you first that I'm not misunderstanding something.

Thanks,
Mike

**Comment by blanton144** [comment]
Also, for Travis, I wonder if I'm doing something non-standard for the cCadenceCore Extension. I'm not too familiar with setup.py so may have done something a little wrong there, even if it works when you and I build it ...

**Comment by johndonor3** [comment]
Hi Mike,

I was able to recreate that error at Utah, and I think it's an issue with sdssdb version? The latest tag should have this issue fixed, and main definitely does. I'm running from main, and I now get a different error that's probably related to me having trouble building and deploying roboscheduler at Utah (it's about CadenceCore, and it doesn't happen on my machine where I can "python setup.py build" and "python setup.py develop" without issue). I'll try to fight that later, but you might able to solve it more quickly.

Thanks,
John

**Pull request merged**
