### PR TITLE
remove all mentions of 'instrument'

### PR DESCRIPTION
**Pull request by johndonor3**
I think I've very thoroughly purged instrument, including from the C. I was able to build and install in a new virtual environment and test functionality. I think it's all good? 

@blanton144 if you could double check that it builds for you that would make me feel better.

Thanks!

### CODE REVIEW

**Comment by johndonor3** [comment]
@blanton144 If you've had a chance to look at this I can try to merge it. But I definitely feel better about merging this fairly significant change if you've had a chance to compile and run the test suite successfully.

**Comment by johndonor3** [comment]
@blanton144 I merged master into the branch and fixed a small issue that I had caused in a test case. Should be good for review and merge to master.

**Comment by blanton144** [comment]
All the tests passed, and the upstream changes to robostrategy are straightforward.

**Comment by johndonor3** [comment]
Awesome. Thanks Mike!

**Pull request merged**
